### PR TITLE
Linting

### PR DESCRIPTION
**Pull request by timothystewart6**
Hi.  I noticed there were some linting errors when running `eslint .` so I opened a PR to fix them.

* Added ignore for Intellij configs
* Fixed linting errors.

Also, if you don't mind, I could create an `npm` script to lint in this PR or a new one (since it would be a new feature).

### CODE REVIEW

**Comment by jeffwilcox** [comment]
Thanks, though oddly `eslint .` has been relatively clean in the `develop` branch... can you confirm that you're using the lint configuration file in the repo and also basing off of the `develop` branch?

Happy to help you get this contribution in but do note that a CLA will be required.

The current `npm test` script also includes the eslint call, but a dedicated linting script would be fine, too - might as well create a separate PR for that.

**Comment by timothystewart6** [comment]
Sure thing.  I signed the CLA but it looks like the tag hasn't updated yet.  I have another PR open and it has the correct tag.  Not sure how the bot works but maybe it hasn't updated this PR yet.  

I am using the eslint config from this repo.  I think the root cause is that  `npm test` script isn't correctly running `eslint`.  It always passes (maybe this is how no lint errors ever come back).  If you run it from the global node module `eslint .` it will return lint errors.  

With the current config, adjusting `.eslintrc.json` to something like:

```
"indent": [
            "error",
            222222
        ],
```

still won't yield errors unless you run it from your global node modules.  I can open a separate PR to fix/create the linting script.

**Comment by timothystewart6** [comment]
Ah, I see what's going on.  You're right.  It is working fine with this version of `"eslint": "^3.17.1",` however it looks like it correctly catches this lint in `v4.0.0` (which I installed globally per the README).

`eslint` should catch this since new lines should have an indent of 2 however it is not currently catching it in this version.

**Comment by jeffwilcox** [comment]
Closing & reopening to see if the CLA status updates.

**Comment by jeffwilcox** [comment]
Appreciate the linting here, and especially the lint + fix script, that will be handy.

I'm going to hold off on immediately accepting this pull request; there's a set of changes (some of which are not yet public) that will be integrated in the coming week, including a rather painful refactoring. To keep that in-progress work merging without too many conflicts I'll hold off. Hope you understand.

Will update this thread if we are able to accept this one.

**Comment by timothystewart6** [comment]
No worries!  Fixing the lint was super easy so no worries there.

**Comment by jeffwilcox** [comment]
With the refactor now in `develop` at least, I'm going to close this PR. Since the newer `eslint` will help fix up, it looks like there's a good path forward.

**Pull request closed without merging**
