### PR TITLE
Update a couple of references to the new api code location

### PR DESCRIPTION
**Pull request by tarkatronic**
I was just working on another branch and noticed this breaking, related to the work merged earlier today.

### CODE REVIEW

**Comment by jeffwilcox** [comment]
@tarkatronic would you mind sharing/submitting a editor settings file or vscode settings for the auto-fix linting you have happening? I'd love to stay consistent.

**Comment by tarkatronic** [comment]
@jeffwilcox You know, it's interesting... I'm pretty sure I'm using default settings; at least, I can't recall specifically tweaking anything. I can try to take a look through though.

That said, I would like to offer an alternative -- setting up a config for `typescript-eslint`, which would then be able to just "fix", then offer linting going forward. I tend to avoid, if at all possible, committing editor config files to git; especially with open source, there's no telling what editor people might be using. :smile:

**Comment by jeffwilcox** [comment]
@tarkatronic great point.

**Comment by tarkatronic** [comment]
@jeffwilcox I checked my `settings.json` and it looks like the only related setting I've touched is:

```json
    "editor.formatOnSave": true,
```

So without any other configuration in place, it looks like I'm just using default JS/TS styling, whatever the TypeScript extension uses.

**Pull request merged**
